# Generated by Django 5.2.17 on 2026-10-05 07:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tên sự kiện')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('location', models.CharField(max_length=200, verbose_name='Địa điểm')),
                ('start_time', models.DateTimeField(verbose_name='Bắt đầu')),
                ('end_time', models.DateTimeField(verbose_name='Kết thúc')),
                ('capacity', models.PositiveIntegerField(blank=True, help_text='Để trống nếu không giới hạn', null=True, verbose_name='Số lượng tối đa')),
                ('checkin_token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='members.department', verbose_name='Ban phụ trách')),
            ],
            options={
                'verbose_name': 'Sự kiện',
                'verbose_name_plural': 'Sự kiện',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='Đăng ký lúc')),
                ('checked_in_at', models.DateTimeField(blank=True, null=True, verbose_name='Điểm danh lúc')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.event', verbose_name='Sự kiện')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_registrations', to=settings.AUTH_USER_MODEL, verbose_name='Thành viên')),
            ],
            options={
                'verbose_name': 'Đăng ký sự kiện',
                'verbose_name_plural': 'Đăng ký sự kiện',
                'ordering': ['registered_at'],
                'constraints': [models.UniqueConstraint(fields=('event', 'user'), name='unique_event_user')],
            },
        ),
    ]
