# Generated by Django 5.2.17 on 2026-10-04 08:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('content', models.TextField(verbose_name='Nội dung')),
                ('pinned', models.BooleanField(default=False, verbose_name='Ghim lên đầu')),
                ('ai_generated', models.BooleanField(default=False, editable=False, verbose_name='Viết nháp bằng AI')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, help_text='Để trống nếu gửi toàn CLB', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to='members.department', verbose_name='Gửi tới ban')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to='events.event', verbose_name='Sự kiện liên quan')),
            ],
            options={
                'verbose_name': 'Thông báo',
                'verbose_name_plural': 'Thông báo',
                'ordering': ['-pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MeetingMinute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tên cuộc họp')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Ngày họp')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Địa điểm')),
                ('raw_notes', models.TextField(verbose_name='Ghi chép cuộc họp')),
                ('summary', models.TextField(blank=True, verbose_name='Tóm tắt')),
                ('ai_summarized_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attendees', models.ManyToManyField(blank=True, related_name='meetings_attended', to=settings.AUTH_USER_MODEL, verbose_name='Người tham dự')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='minutes_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Biên bản họp',
                'verbose_name_plural': 'Biên bản họp',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
