# Generated by Django 5.2.17 on 2026-10-04 12:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Tên ban')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('head', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to=settings.AUTH_USER_MODEL, verbose_name='Trưởng ban')),
            ],
            options={
                'verbose_name': 'Ban',
                'verbose_name_plural': 'Ban',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('head', 'Trưởng ban'), ('deputy', 'Phó ban'), ('member', 'Thành viên')], default='member', max_length=10, verbose_name='Chức vụ')),
                ('joined_at', models.DateField(default=django.utils.timezone.localdate, verbose_name='Ngày tham gia')),
                ('is_active', models.BooleanField(default=True, verbose_name='Còn hoạt động')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='members.department', verbose_name='Ban')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL, verbose_name='Thành viên')),
            ],
            options={
                'verbose_name': 'Thành viên trong ban',
                'verbose_name_plural': 'Thành viên trong ban',
                'ordering': ['department__name', 'user__first_name'],
                'constraints': [models.UniqueConstraint(fields=('user', 'department'), name='unique_user_department')],
            },
        ),
    ]
